In [76]:
import numpy as np
import pandas as pd

In [38]:
class DecisionTreeClassifier():

    def __init__(self, min_samples_split):
        self.min_samples_split=min_samples_split
        self.tree={'level':0,
                   'type':'root',
                   'feature':None,
                   'threshold':None,
                   'left':None,
                   'right':None,
                   }
    
    def fit(self, X_train, y_train):
        def node_construction(subtree,subX,suby):
            'modify tree ? to be tested'
            splits={}
            for index,col in subX.iteritems():
                splits[index]=np.sort(col.sample(1000,replace=True).unique())
                splits[index]=list((splits[index][1:]+splits[index][:-1])/2)
            splits=[[(key,threshold) for threshold in value] for key,value in splits.items()]
            splits=[y for x in splits for y in x]

            for split in splits:
                mask=subX[split[0]]>split[1]
                y_left=suby[mask]
                y_right=suby[-mask]
                
        node_construction(self.tree, X_train, y_train, min_samples_split=self.min_samples_split)

    def predict(self, X_test):
        def node_navigation(subtree, X_sample):
            '''X_sample : df with a single line'''
            if tree['type']=='leaf':
                return subtree['category']
            if X_sample[subtree['feature']]>subtree['threshold']:
                return node_navigation(subtree['right'], X_sample)
            return node_navigation(subtree['left'], X_sample)

        return X.apply(lambda x: node_navigation(self.tree, x), axis=1)

In [39]:
dtc=DecisionTreeClassifier(min_samples_split=10)
dtc.tree={'level': 0,
 'type': 'root',
 'feature': 'aa',
 'threshold': 0.5,
 'left': None,
 'right': None}

In [40]:
dtc.tree['left']={'level': 1,
                 'type': 'root',
                 'feature': 'aa',
                 'threshold': 0.25,
                 'left': {'level':2,'type':'leaf','category':1},
                 'right': {'level':2,'type':'leaf','category':0}}
dtc.tree['right']={'level':1,
                  'type':'leaf',
                  'category':1}

In [95]:
X_test=pd.DataFrame({'aa':[0.1,0.2,0.7],'bb':[1,0,1],'cc':[1,1,1]})

In [96]:
dtc.predict(X_test)

0    1
1    1
2    1
dtype: int64

In [97]:
X_test

aa  bb  cc
0  0.1   1   1
1  0.2   0   1
2  0.7   1   1

In [105]:
splits={}
for index,col in X_test.iteritems():
    splits[index]=np.sort(col.sample(1000,replace=True).unique())
    splits[index]=list((splits[index][1:]+splits[index][:-1])/2)
splits

{'aa': [0.15000000000000002, 0.44999999999999996], 'bb': [0.5], 'cc': []}

In [106]:
splits=[[(key,threshold) for threshold in value] for key,value in splits.items()]
splits=[y for x in splits for y in x]
splits

[('aa', 0.15000000000000002), ('aa', 0.44999999999999996), ('bb', 0.5)]

In [64]:
ser=pd.Series([4,2,3,4])
ser

0    4
1    2
2    3
3    4
dtype: int64

In [83]:
np.random.choice(ser.unique(),6)

array([2, 4, 4, 2, 2, 3])

In [89]:
np.sort(ser.sample(1000,replace=True).unique())

array([2, 3, 4])

In [77]:
npp=np.sort(ser.unique())

In [78]:
npp

array([2, 3, 4])

In [80]:
(npp[1:]+npp[:-1])/2

array([2.5, 3.5])

In [107]:
X_test

aa  bb  cc
0  0.1   1   1
1  0.2   0   1
2  0.7   1   1

In [109]:
y_test=pd.DataFrame({'target':[0,0,1]})

In [110]:
y_test

target
0       0
1       0
2       1

In [115]:
mask=X_test['aa']>0.5

In [116]:
-mask

0     True
1     True
2    False
Name: aa, dtype: bool

In [117]:
mask

0    False
1    False
2     True
Name: aa, dtype: bool